### ISSUE TITLE
Flutter owns our main.dart?

### ISSUE THREAD

**Issue by LeitMoth** [danielajgr/Hendrix-Arboretum#46]
https://github.com/danielajgr/Hendrix-Arboretum/blob/f9c23b12f496297c4384fd00f3d7e7f6512aef34/final_project/lib/main.dart#L1-L3

**Comment by LeitMoth** [comment]
Assigning @danielajgr this issue because she committed the above comment to the repo.

**Comment by LeitMoth** [comment]
It's probably not a huge deal, but should also probably be resolved.

**Comment by danielajgr** [comment]
I used the code that the flutter demo used, main had all the routing stuff so I just used that: here is the license they have: // Copyright 2020 The Flutter Authors. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`

**Comment by LeitMoth** [comment]
I think the protocol is to include this license renamed, alongside the main license (which I still need to decide), then updating the comment above to refer to the renamed license.

I don't remember the details, so you may want to ask Dr. Goadrich.

**Comment by LeitMoth** [comment]
I had some additional license questions so I decided to go ahead and email him, I should know what to do soon.
